//
//  FluShotProviders.swift
//  Flu Shot Finder
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class FluShotProviders: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _storeName: String?
    var _perks: Set<String>?
    var _price: NSNumber?
    var _zipCode: NSNumber?
    
    class func dynamoDBTableName() -> String {
        
        return "flushotfinder-mobilehub-698310344-FluShotProviders"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_storeName"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_storeName" : "storeName",
            "_perks" : "perks",
            "_price" : "price",
            "_zipCode" : "zipCode",
        ]
    }
}
